### PR TITLE
Get requests with response payload

### PR DESCRIPTION
**Pull request by DenverM80**
Refactor noisy logic from templates into RequestHelper.

Requests fall into categories based on HEAD, Request with Response Payload, Request with Request Payload (next), or Request with both Request and Response Payload (after that)

### CODE REVIEW

**Comment by DenverM80** [comment]
Not sure why this says "All checks have failed - Travis CI shows all 3 tests passed...???"

**Comment by DenverM80** [comment]
updated; fixed test failures

**Comment by RachelTucker** [comment]
The pull request is out of date

**Comment by DenverM80** [comment]
updated

**Pull request closed without merging**
